### ISSUE TITLE
Containerize the Context Broker 

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#10]
- [x] Build docker images for the Context Broker components and push to docker registry (private repo to be provided)
- [x] Define helm charts/manifest files for the Context Broker
- [x] Deploy the Context Broker components on existing Kubernetes setup
- [x] #54

**Comment by Subrahmanya-tcs** [comment]
Containerized the existing scorpio components and pushed to ibn40/digitaltwin private repository.
Building docker images for the new scorpio components in progress.

**Comment by subhommitra** [comment]
Deployed the existing scorpio components on k8s using helm charts. Docker images were pulled from ibn40/digitaltwin repo. "HistoryManager" image throws authorization error during pull, other components are in Running state.

**Comment by subhommitra** [comment]
Container image pull issues have been resolved. Helm charts for all Context Broker components have been created and tested.

**Comment by swathichittajallu** [comment]
Closing this issue as all tasks are completed.
