### ISSUE TITLE
Develop API definitions for the Context Broker APIs in Swagger.

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#17]

**Comment by yogesh-nextgen** [comment]
[NGSI-LD-OpenAPI-Auth-specs.zip](https://github.com/IndustryFusion/DigitalTwin/files/7467103/NGSI-LD-OpenAPI-Auth-specs.zip)

The attached specifications contain security schemes added to the standard NGSI-LD OpenAPI specifications defined by ETSI ISG CIM. Reference API definitions taken from https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/tree/master/spec/updated
