### ISSUE TITLE
Develop code to relay the updates on Context Broker objects to Kafka topics in debezium format

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#18]
- [x] #21
- [ ] #25
- [ ] #26
- [x] #31

**Comment by yogesh-nextgen** [comment]
Scorpio Broker code analysis is in progress. Entity Manager service in Scorpio Broker uses PostgreSQL as persistence layer to store its state. For this state to be sent to Kafka topics in Debezium format, the corresponding tables in PostgreSQL/Entity manager APIs need to be identified.
Also, Scorpio Broker has Kafka implementations in its microservices to exchange data over Kafka topics using Spring messaging framework. History Manager, other services act as Kafka consumers to store this data in PostgreSQL and for other operations respectively.

**Comment by swathichittajallu** [comment]
- [ ] Install kafka connect for PostgreSQL using Strimzi operator to integrate Kafka and PostgreSQL

**Comment by wagmarcel** [comment]
Decision: 
- Implementing a consumer which will process the debezium format from postgres entity table and puts it into respective topics based on entity name
- Put it capability to provide entity in key/value format, i.e. the values are directly given after the field names.
- Remove json-ld expansion of field names

**Comment by yogesh-nextgen** [comment]
[required-json-payload.txt](https://github.com/IndustryFusion/DigitalTwin/files/7511995/required-json-payload.txt)

The file attached contains the agreed payload structure.

**Comment by yogesh-nextgen** [comment]
[required-json-payload-with-keyValue-pair.txt](https://github.com/IndustryFusion/DigitalTwin/files/7517599/required-json-payload-with-keyValue-pair.txt)

The file attached contains the agreed payload structure with key value data.

**Comment by wagmarcel** [comment]
@yogesh-nextgen I think key-value format should look like this:
 {
"id": "house2:smartrooms:room1",
 "type": "Room",
"@context ": [
    {
    "Room ":  "urn:mytypes:room ",
    "isPartOf ":  "myuniqueuri:isPartOf ", 
    "temperature ":  "myuniqueuri:temperature"
    }, 
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ],
"isPartOf ":  "smartcity:houses:house2",
"temperature":  23
}

**Comment by yogesh-nextgen** [comment]
[agreed-json-payload.txt](https://github.com/IndustryFusion/DigitalTwin/files/7543894/agreed-json-payload.txt)

The file attached contains the final agreed payload.

**Comment by yogesh-nextgen** [comment]
Made first commit of Debezium Adapter and Development of the Debezium Adapter service is in progress.

**Comment by yogesh-nextgen** [comment]
Completed development including unit test cases. End to end test flow on kubernetes is completed. Testing with different types of entity payloads is in progress.

**Comment by yogesh-nextgen** [comment]
Completed end to end testing on kubernetes.
