### ISSUE TITLE
Install kafka connect for PostgreSQL using Strimzi operator to integrate Kafka and PostgreSQL

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#21]

**Comment by Subrahmanya-tcs** [comment]
kafka connect for PostgreSQL using Strimzi operator in progress

**Comment by yogesh-nextgen** [comment]
KafkaConnect (using custom image) and KafkaConnector using Strimzi were deployed.

**Comment by Subrahmanya-tcs** [comment]
Deployed kafkaConnect (using custom image) and kafkaConnector , and tested for integration of kafka and PostgreSQL
