### ISSUE TITLE
Install Keycloak using operator pattern on K8s cluster.

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#22]

**Comment by subhommitra** [comment]
Updates: 

- Keycloak recommends using OLM
- OLM installed successfully, but unable to access OLM dashboard
- Installed nginx Ingress Controller, pending configuration for accessing OLM and Keycloak

**Comment by swathichittajallu** [comment]
Keycloak deployed using operator. Accessible over http. Need to enable https and provide SSL termination at Nginx controller.

**Comment by yogesh-nextgen** [comment]
Keycloak deployed using operator. enabled https and provided SSL termination at Nginx controller, enabled external database support for Keycloak, need to enable SSL termination for external database communication.

**Comment by yogesh-nextgen** [comment]
Keycloak deployed using operator. provided SSL termination at Nginx controller and  for external database communication.

For external database communication different types of SSL settings can be done, that comes with different level of security for database communication. Completed testing with SSLMODE allow, in which Keycloak generates self sign certificates for db communication (Refer to the PostgreSQL documentation link here) https://www.postgresql.org/docs/current/libpq-ssl.html
