### ISSUE TITLE
Setup local Digital Twin (including scorpio, alerta, keycloak) environment

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#227]
https://github.com/IndustryFusion/DigitalTwin
Locale setup with helm (works on ubuntu).

**Comment by wagmarcel** [comment]
in preparation by Iteratec

**Comment by mreuder-iteratec** [comment]
Setup not successful so far - neither on the VM, nor locally, nor by other colleagues. --> Clarification of further procedure
