### ISSUE TITLE
(industry fusion application) Fleetmanager:  Machine data Export in NGSI_LD (AND SHACL)

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#231]
### Acceptance Criteria

1. Fleet manager exports data as NGSI-LD and SHACL.
2. NGSI-LD data complies with  https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf and can be imported into Scorpio broker
3. SHACL data complies with https://www.w3.org/TR/shacl/ and is accepted by rdflib's pyshacl

**Comment by wagmarcel** [comment]
NGSI-LD base object contains information not streamed/changed from machines (e.g. no state information)

**Comment by tlukman** [comment]
Feedback von Marcel - Wunsch für den Export:
Id, Type + Stammdaten
