### ISSUE TITLE
Implementation of RBAC functionality in Context Broker.

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#24]

**Comment by Suvarat211** [comment]
Development is in progress for Entity Manager service in Scorpio Broker.

**Comment by Suvarat211** [comment]
Completed integration of RBAC roles using keycloak for Entity Manager.

**Comment by Suvarat211** [comment]
RBAC support provided for Scorpio Broker services - Entity Manager, Query Manager, Subscription Manager, History Manager and Registry Manager.

**Comment by Suvarat211** [comment]
Testing the RBAC flow via Spring Cloud Gateway

**Comment by Suvarat211** [comment]
Unit test case development to test RBAC is in progress.
Existing test cases in Scorpio services are failing. -DskipTests is being used currently to build the jars and images and this is an open issue. Reference: https://github.com/ScorpioBroker/ScorpioBroker/issues/250
Also exploring possibilities to disable Spring Security on these test cases.

**Comment by Suvarat211** [comment]
Testing the RBAC flow via Spring Cloud Gateway is completed.

**Comment by swathichittajallu** [comment]
Unit test cases implemented to support RBAC for all NGSI-LD compliant Scorpio APIs.  PR created.
