### ISSUE TITLE
Install PostgreSQL using Zalando operator on K8s cluster

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#25]

**Comment by subhommitra** [comment]
Created helm (v3) charts using the K8s manifests provided by Zalando. Deployed the "minimal" variant of the cluster.

**Comment by subhommitra** [comment]
Zalando postgres operator is being used to bring up the DB and DB users (with necessary permissions) as required by Scorpio. This behaviour is configurable using postgres operator helm charts.
