### ISSUE TITLE
Define Semantic serialization format for IFF Ecosystem-Manager

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#4]
Define and document input and output formats (in the semantic web context) of
- [x] Ecosystem Manager
- [x] Fleet Manager
- [x] Factory Manager

Formats for 3 specific use-cases are required:
1. For the serialization (import and export) of content data in the fusion application
2. For the export of semantic models out of the fusion application towards the digital twin side of the ecosystem
3. For the definition of the actual asset in the digital twin itself (NGSI-LD)

- [x] It should also be decided and documented whether 1 and 2 above complement each other (i.e. 80% + 20%) or overlap (i.e. 100% + 80%). We could use 2 for the validation of the NGSI-LD of the asset.

**Comment by davidlane-iteratec** [comment]
This is proposed to be completed with the following revision:
https://github.com/IndustryFusion/DigitalTwin-WIP/blob/9afa87b9e1db6ec05a7a1a3659d26a320c76bbba/Import_Export.md
