### ISSUE TITLE
[TASK] Update Debezium bridge to use datasetId

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#503]
datasetId is the new index, but for the time being we keep index. For instance:
 "https://industry-fusion.com/types/v0.9/state": [
        {
            "type": "Property",
            "value": "OFF"
        },
        {
            "type": "Property",
            "value": "ON"
        }
    ],

Will create only one attribute with index=0 and datasetId="@none" with value="ON"

 "https://industry-fusion.com/types/v0.9/state": [
        {
            "type": "Property",
            "value": "OFF"
        },
        {
            "type": "Property",
            "value": "ON"
        },
,
        {
            "type": "Property",
            "value": "ONNN",
            "datasetId": "urn:iff:test:123"
        }

    ],

is transleted to 2 properties
index=0, datasetId="@none", value="ON"
index=1, datasetId="urn:iff:test:123", value="ONNN"

"@none" has always index=0
other indexes after lexicographic ordering, e.g. index of field with "datasetId"="urn:iff:test:a" is before "datasetId"="urn:iff:test:b"

**Comment by MericFeyz** [comment]
For an entity with the following Property with multiple values: 

"https://industry-fusion.com/types/v0.9/hasWorkpiece": [
        {
            "type": "Relationship",
            "object": "urn:workpiece-test:12345",
            "datasetId": "urn:iff:test:123"
        },
        {
            "type": "Relationship",
            "object": "urn:workpiece-test:23456",
            "datasetId": "urn:iff:test:125"
        }
    ],

When using Scorpio 4.1.11, we get the following Key-Value pair from debezium:

"https://industry-fusion.com/types/v0.9/hasWorkpiece" : [
  {
    "@type": [
      "https://uri.etsi.org/ngsi-ld/Property",
    ],
    "https://uri.etsi.org/ngsi-ld/hasValue": [
      {
        "@type": [
          "https://uri.etsi.org/ngsi-ld/Relationship",
        ],
        "https://uri.etsi.org/ngsi-ld/createdAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/datasetId": [
          {
            "@id": "urn:iff:test:123",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/hasObject": [
          {
            "@id": "urn:workpiece-test:12345",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/modifiedAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
      },
      {
        "@type": [
          "https://uri.etsi.org/ngsi-ld/Relationship",
        ],
        "https://uri.etsi.org/ngsi-ld/createdAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/datasetId": [
          {
            "@id": "urn:iff:test:125",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/hasObject": [
          {
            "@id": "urn:workpiece-test:23456",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/modifiedAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
      },
    ],
    "https://uri.etsi.org/ngsi-ld/createdAt": [
      {
        "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
        "@value": "2024-02-09T14:16:35Z",
      },
    ],
    "https://uri.etsi.org/ngsi-ld/modifiedAt": [
      {
        "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
        "@value": "2024-02-09T14:16:35Z",
      },
    ],
  },
]

Of notice are:
1) Value of the KV Pair is an array of one. This is the same for every property of the entities used in e2e tests of the debezium bridge. (Only modified some properties with the datasetIds). We however currently iterate over this array expecting multiple elements and we create an parsed "obj" for every iteration. We also set the "obj.index" during these iterations. This results in each property having an index of 0.
2) This only element of the array has @type, modifiedAt, createdAt and hasValue (in this case, otherwise hasObject) keys. The hasValue key also has an array with the same number of elements as the number of attributes of the property, and the attributes are represented here with their own @type, modifiedAt, createdAt and hasValue (or hasObject again). However currently we use JSON.stringify() to turn the entire hasValue array into a string and set obj["https://uri.etsi.org/ngsi-ld/hasValue"] to this string instead of parsing these individual values, which goes deep. In the case of a property like the following:

"https://industry-fusion.com/types/v0.9/jsonValueArray": [
        {
            "type": "Property",
            "value": {
                "https://industry-fusion.com/types/v0.9/my": "json1"
            }
        },
        {
            "type": "Property",
            "value": {
                "type": "https://industry-fusion.com/types/v0.9/myJsonType",
                "https://industry-fusion.com/types/v0.9/my": "json2"
            }
        }
    ],

We receive the following value array:

[
  {
    "@type": [
      "https://uri.etsi.org/ngsi-ld/Property",
    ],
    "https://uri.etsi.org/ngsi-ld/hasValue": [
      {
        "@type": [
          "https://uri.etsi.org/ngsi-ld/Property",
        ],
        "https://uri.etsi.org/ngsi-ld/hasValue": [
          {
            "https://industry-fusion.com/types/v0.9/my": [
              {
                "@value": "json1",
              },
            ],
          },
        ],
        "https://uri.etsi.org/ngsi-ld/createdAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/modifiedAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
      },
      {
        "@type": [
          "https://uri.etsi.org/ngsi-ld/Property",
        ],
        "https://uri.etsi.org/ngsi-ld/hasValue": [
          {
            "@type": [
              "https://industry-fusion.com/types/v0.9/myJsonType",
            ],
            "https://industry-fusion.com/types/v0.9/my": [
              {
                "@value": "json2",
              },
            ],
          },
        ],
        "https://uri.etsi.org/ngsi-ld/createdAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
        "https://uri.etsi.org/ngsi-ld/modifiedAt": [
          {
            "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
            "@value": "2024-02-09T14:16:35Z",
          },
        ],
      },
    ],
    "https://uri.etsi.org/ngsi-ld/createdAt": [
      {
        "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
        "@value": "2024-02-09T14:16:35Z",
      },
    ],
    "https://uri.etsi.org/ngsi-ld/modifiedAt": [
      {
        "@type": "https://uri.etsi.org/ngsi-ld/DateTime",
        "@value": "2024-02-09T14:16:35Z",
      },
    ],
  },
]

Of notice is the second element of the hasValue array, where you get multiple nested JSON objects. The obj.valueType that we require to be set is in the hasValue object of the 3rd level with the type: "https://industry-fusion.com/types/v0.9/myJsonType". However with current implementation, even if we iterate over the elements of the first hasValue array, we still would get the obj.valueType="https://uri.etsi.org/ngsi-ld/Property", because our assumptions do not account for this. This also would mean that we would not be able to reach to the datasetId if it is present, and would mistakenly set it to '@none'. This means that surface level iteration will only work so far and a solution involving recursion inside the JSON objects might be needed.

**Comment by MericFeyz** [comment]
Based on our findings we have deduced that an entity with multiple attributes inserted into Scorpio results in a slightly different entity than expected according to the specification. Further tests were made with clean Scorpio releases with versions 4.1.11 and 4.1.15, and the results stayed the same. I have created an [issue](https://github.com/ScorpioBroker/ScorpioBroker/issues/532) on this bug in the ScorpioBroker repository.

**Comment by wagmarcel** [comment]
Decision: Update the DatasetId handling with ver3 of Scorpio

**Comment by MericFeyz** [comment]
Implemented DatasetId handling with ver3 of Scorpio (kafka-config-topic branch): 

With an entity with multiple attributes in one property like the following:

```
{
  "id":"urn:ngsi-ld:Vehicle:A4567",
  "type":"Vehicle",
  "speed":[
    {
      "type":"Property",
      "value":55,
      "source":{
        "type":"Property",
        "value":"Speedometer"
      },
      "datasetId":"urn:ngsi-ld:Property:speedometerA4567-speed"
    },
    {
      "type":"Property",
      "value":1000,
      "source":{
        "type":"Property",
        "value":"Speedometer"
      }
    },
    {
      "type":"Property",
      "value":54.5,
      "source":{
        "type":"Property",
        "value":"GPS"
      },
      "datasetId":"urn:ngsi-ld:Property:gpsBxyz123-speed"
    },
    {
      "type":"Property",
      "value":57.5,
      "source":{
        "type":"Property",
        "value":"GPS"
      }
    },
    {
      "type":"Property",
      "value":59.5,
      "source":{
        "type":"Property",
        "value":"GPS"
      },
      "datasetId":"urn:ngsi-ld:Property:ZZZZZZZ"
    }
  ],
  "@context":[
    {
      "Vehicle":"http://example.org/Vehicle",
      "speed":"http://example.org/speed",
      "source":"http://example.org/hasSource"
    },
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
  ]
}
``` 
It results in the following messages in the ```iff.ngsild.attributes``` channel, with distinct attributes sorted lexicologically according to their datasetIds and then indexed based on their sorting:
```
% Reached end of topic iff.ngsild.attributes [0] at offset 182
{"id":"urn:ngsi-ld:Vehicle:A4567\\http://example.org/speed","entityId":"urn:ngsi-ld:Vehicle:A4567","name":"http://example.org/speed","https://uri.etsi.org/ngsi-ld/datasetId":"@none","type":"https://uri.etsi.org/ngsi-ld/Property","https://uri.etsi.org/ngsi-ld/hasValue":57.5,"nodeType":"@value","index":0}
{"id":"urn:ngsi-ld:Vehicle:A4567\\http://example.org/speed","entityId":"urn:ngsi-ld:Vehicle:A4567","name":"http://example.org/speed","https://uri.etsi.org/ngsi-ld/datasetId":"urn:ngsi-ld:Property:gpsBxyz123-speed","type":"https://uri.etsi.org/ngsi-ld/Property","https://uri.etsi.org/ngsi-ld/hasValue":54.5,"nodeType":"@value","index":1}
{"id":"urn:ngsi-ld:Vehicle:A4567\\http://example.org/speed","entityId":"urn:ngsi-ld:Vehicle:A4567","name":"http://example.org/speed","https://uri.etsi.org/ngsi-ld/datasetId":"urn:ngsi-ld:Property:speedometerA4567-speed","type":"https://uri.etsi.org/ngsi-ld/Property","https://uri.etsi.org/ngsi-ld/hasValue":55,"nodeType":"@value","index":2}
{"id":"urn:ngsi-ld:Vehicle:A4567\\http://example.org/speed","entityId":"urn:ngsi-ld:Vehicle:A4567","name":"http://example.org/speed","https://uri.etsi.org/ngsi-ld/datasetId":"urn:ngsi-ld:Property:ZZZZZZZ","type":"https://uri.etsi.org/ngsi-ld/Property","https://uri.etsi.org/ngsi-ld/hasValue":59.5,"nodeType":"@value","index":3}
% Reached end of topic iff.ngsild.attributes [0] at offset 186
```
E2E tests pass, Pull request pending discussion.

**Comment by MericFeyz** [comment]
Discussion: Data is being lost after the ngsi-ld run
After entity creation:
```
kvdata                | {"@id": "urn:ngsi-ld:Vehicle:A4567", "@type": ["http://example.org/Vehicle"], "http://example.org/speed": [[{"@value": 55}], [{"@value": 1000}], [{"@value": 54.5}], [{"@value": 57.5}], [{"@value": 59.5}]]}
```
After the ngsi-ld KafkaSync addition:
```
kvdata                | {"@id": "urn:ngsi-ld:Vehicle:A4567", "@type": ["http://example.org/Vehicle"], "http://example.org/speed": [[{"@value": 55}], [{"@value": 54.5}], [{"@value": 59.5}], [{"@value": "55"}], [{"@value": "54.5"}]], "https://industry-fusion.com/types/v0.9/metadata/kafkaSyncOn": [{"@value": "1712321957364.56wbt"}]}
```
