### ISSUE TITLE
Perform End to end integration tests for RBAC & Debezium service features on Kubernetes

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#54]

**Comment by swathichittajallu** [comment]
Completed one round of tests.

**Comment by yogesh-nextgen** [comment]
Completed end to end testing for RBAC, Debezium bridge with code from the latest branch with all PRs merged. 
(Refer to the branch link here TCS-development) https://github.com/IndustryFusion/ScorpioBroker/tree/TCS-development

**Comment by swathichittajallu** [comment]
@yogesh-nextgen You may close this issue once after the update API issue in Scorpio is fixed and tested.

**Comment by yogesh-nextgen** [comment]
Update API issue in Scorpio does not require any fixes, Completed end to end testing for RBAC, Debezium bridge.
