### ISSUE TITLE
Validate & test RBAC functionality in Alerta. Extend/test its integration with Keycloak. 

### ISSUE THREAD

**Issue by swathichittajallu** [IndustryFusion/DigitalTwin#78]

**Comment by yogesh-nextgen** [comment]
Integrated Alerta with Keycloak as a authentication provider, Validation & testing of RBAC functionality in Alerta is done.

For authorization in Alerta, roles and scopes are defined (Refer to the Alerta documentation link here) https://docs.alerta.io/authorization.html#scopes-and-permissions
