### ISSUE TITLE
NGSI-LD - Authorization concept

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#8]
- Fiware defines multi tenancy headers
- Can it be abstracted only based on keycloak?

- [x] #13
- [ ] task 1
- [ ] task 2

**Comment by subhommitra** [comment]
Analysis of multi-tenancy capabilities of Scorpio has been completed. Detailed documentation for complete multi-tenancy concept including Keycloak is being prepared.
